# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f528c2c765ca0f162f5f13c8bb78180bad857fe632b731f0e5ab33697d8143cb74ef0af2e87f537bed8fdf0a75d07de1858a13efff9f639a47d7d036e1dcae

test:
  secret_key_base: dd0a8936d31b7d96aa025e9b44e875f6a961b09dbbe1ad7a7ae54491b555c082b499e5f81e57373ff724d3f58a3f17a3c718025414da77d9f1c79ddb942a90b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
